Repository nebari-dev/governance, pull requests merged in 2022-12, with the labels that each got.

#23 Add CoC documents
  CODE_OF_CONDUCT.md
  code-of-conduct/coc_details.md
  code-of-conduct/coc_diversity_statement.md
  code-of-conduct/coc_enforcement.md
  code-of-conduct/coc_reporting.md
Labels: type: enhancement 💅🏼, area: governance 🧭, area: community health 🌱, status: approved 💪🏾

#24 🔄 Synced file(s) with nebari-dev/.github
  .github/ISSUE_TEMPLATE/config.yml
Labels: type: file sync ♻️

#28 Remove release details & add analytics info
  README.md
  Releases.md
  analytics.md
Labels: area: documentation 📖, type: enhancement 💅🏼, area: governance 🧭, needs: review 👀
